"""followers

Revision ID: 96427a22b297
Revises: 57c2d5dc15f2
Create Date: 2023-06-18 04:25:26.957213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96427a22b297'
down_revision = '57c2d5dc15f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
